### ISSUE TITLE
Incompatible with Quilt because of simple json

### ISSUE THREAD

**Issue by MeeniMc** [Fourmisain/CreativeOnePunch#1]
This mod, **as downloaded from CurseForge**, is currently incompatible with Quilt: 

there is a small problem in the `fabric.mod.json`: line 2 that needs to be changed

```diff
- 	"schemaVersion": 1.0,
+	"schemaVersion": 1,
```

Interestingly, the code on this GitHub doesn't have that same bug as the CF release for any of the branches??

**Comment by Fourmisain** [comment]
Hm... This is quite confusing.

So the reason why the `schemaVersion` turned into `1.0` is because of the way this mod is built.
It's actually 3 separate builds that get merged with a plugin I call Glue. One thing Glue does is merge the different `fabric.mod.json`s by reading them via Gson, merging the resulting `Map` and writing one output file via Gson again.

Gson by default interprets all numbers as double values, hence the 1 is then written as 1.0.
I've now [fixed this ](https://github.com/Fourmisain/CreativeOnePunch/commit/ca41809f794abafd3a94623334aca0e0bed8b472) by giving Gson the `ToNumberPolicy.LONG_OR_DOUBLE` policy, which will parse the 1 as a long and hence write it as a 1 again.

---

Now to the confusing bit:
According to https://json-schema.org/understanding-json-schema/reference/numeric.html

> The integer type is used for integral numbers. **JSON does not have distinct types for integers and floating-point values**. Therefore, the presence or absence of a decimal point is not enough to distinguish between integers and non-integers. **For example, 1 and 1.0 are two ways to represent the same value in JSON. JSON Schema considers that value an integer no matter which representation was used.**

Hence I do not understand why Quilt produces
> MalformedSyntaxException: Found potentially valid JSON5, but invalid JSON while in strict mode $.schemaVersion

Looking into the code, it seems to come down to this line:

https://github.com/QuiltMC/quilt-json5/blob/4e9caa0e5a1c438ac89e683454b8214a8c341163/src/main/java/org/quiltmc/json5/JsonReader.java#L1154

The parser only allows for trailing decimals in JSON5 mode.

This seems to have been introduced in https://github.com/QuiltMC/quilt-json5/commit/ccfa2421de4de72982af8fe9afdf80641d246d02
> A strict JSON only mode has been added which will only parse valid JSON.

I've looked a bit further into this and found the JSON standard - well, actually the 3 of them: [RFC 8259 ](https://datatracker.ietf.org/doc/html/rfc8259), [ECMA-404](https://www.ecma-international.org/publications-and-standards/standards/ecma-404/) and [ISO/IEC 21778:2017](https://www.iso.org/standard/71616.html). They are extremely short and reading them makes it very clear, that there is indeed no such thing as an integer, hence I think Quilt's `JsonReader` is in the wrong here and should probably be patched.

**Comment by MeeniMc** [comment]
New version works as intended

**Comment by EGOIST1372** [comment]
why this issue is closed? there is no new version

**Comment by MeeniMc** [comment]
A new version has been published on Modrinth with the same version number as on CF, but the CF version is actually an older build.
